version: "3.8"

services:
  mcserver:
    build:
      context: ./linux-gsm-container
    container_name: lgsm-mcserver
    ports:
      # Minecraft port
      - "25565:25565"
      # Micro API port (do not change)
      - "8080:8080"
    volumes:
      - mc_volume/lgsm:/${MC_VOLUME}/lgsm
      - mc_volume/serverfiles:/${MC_VOLUME}/serverfiles
    restart: unless-stopped

volumes:
  mc_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/minecraft-data 
