version: "3.8"

services:
  mcserver:
    build:
      context: ./linux-gsm-container
      args:
        JAVA_VERSION: ${JAVA_VERSION}
        PUID: ${PUID}
        PGID: ${PGID}
        MC_USER: ${MC_USER}
        MC_GROUP: ${MC_GROUP}
        MC_VOLUME: ${MC_VOLUME}
        LGSM_COMMAND: ${LGSM_COMMAND}
        TZ: ${TZ}
    container_name: lgsm-mcserver
    environment:
      MC_USER: ${MC_USER}
      MC_GROUP: ${MC_GROUP}
      MC_VOLUME: ${MC_VOLUME}
      LGSM_COMMAND: ${LGSM_COMMAND}
    ports:
      - "25565:25565"
      - "8080:8080"
    volumes:
      - /var/lib/minecraft/minecraft-server-data/serverfiles:${MC_VOLUME}/serverfiles
      - /var/lib/minecraft/minecraft-server-data/lgsm:${MC_VOLUME}/lgsm
    restart: unless-stopped

